name: Sync Config
on:
  release:
    types:
      - released # this will run when a (not-pre-)release is created or was changed from pre-release to a release
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag in form vX.Y.Z'
        required: true
        type: string
jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.release.outputs.release_tag }}
    steps:
      # this is to support both manually trigger workflows, and automatically triggered on release creation
      - name: Determine release tag
        id: release
        env:
          MANUAL_TAG: ${{ inputs.releaseTag }}
        run: |
          if [[ ! -z "${MANUAL_TAG}" ]]; then
            echo "Manually set tag: ${MANUAL_TAG}"
            echo "release_tag=${MANUAL_TAG}" >> "$GITHUB_OUTPUT"
          else
            echo "Tag from release event: ${{ github.event.release.tag_name }}"
            echo "release_tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          ref: 'refs/tags/${{ steps.release.outputs.release_tag }}'

      - name: Skip updates on alpha or beta versions
        if: ${{ contains(steps.release.outputs.release_tag, 'alpha') || contains(steps.release.outputs.release_tag, 'beta') }}
        run: |
          git status
          git log
          echo "skipping updates in platform schema, because the tag is alpha/beta: ${{ steps.release.outputs.release_tag }}"

      - name: Update platform schema in vcluster-config
        if: ${{ ! contains(steps.release.outputs.release_tag, 'alpha') && ! contains(steps.release.outputs.release_tag, 'beta') }}
        run: |
          git status
          git log
          echo "update platform schema"

