name: Upload release asset
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag in form vX.Y.Z'
        required: true
        type: string
jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: upload release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload  "v0.0.8" \
            ./readme.md \
            ./vcluster-*-x.txt \
            --repo hidalgopl/gh-actions-playground \
            --clobber

